### ISSUE TITLE
Option to install node from package instead of compiling it

### ISSUE THREAD

**Issue by xentac** [digitalbutter/cookbook-node#1]
Ubuntu comes with a nodejs package.  Rather than waiting for nodejs to compile on all my servers, it might be nice to use the package instead.

I would be willing to write a patch, if you are open to accept it.

**Comment by eprochasson** [comment]
It does, but the versions provided are super outdated. Moreover, we only deploy LTS version (latest is 10.04...) which I don't think includes nodejs. My personal ubuntu provides nodejs v0.1.97...

However, it's not too complicated to install it using a package, best way would be to have an option to either compile it or install the package. Contribution welcome, or I'll try to spend a bit of time on that later this week.

Thanks for the comments !

**Comment by edbo** [comment]
+1 for allowing this to be included but I don't think it should be the default way at the moment for the reasons mentioned above

**Comment by jellybob** [comment]
Hi there,

I'm just finishing work on allowing the choice between compiling from source or installing from packages where they're available - I actually started writing it before I thought to check if anyone had done it already! 

It's controlled by the attribute node/install_from_source, which defaults to true so that existing users don't get hit by a sudden change.

The code can be found at https://github.com/jellybob/kitchen/tree/node/. I've only tested it on Ubuntu 11.04, which is the only version which currently has a nodejs package. If the cookbook detects that no packages are available then it will raise an error, notifying the user that they should install from source.

It would be great if you could merge this so that I can depend on a maintained node cookbook for my statsd cookbook, which should also allow it to support versions < 11.04.

Jon

**Comment by eprochasson** [comment]
Awesome ! I'll have a look. Thanks a lot.

On Jun 25, 2011 8:54 PM, "jellybob" <
reply@reply.github.com>
wrote:

**Comment by eprochasson** [comment]
I merge your changed and republished the cookbook to chef. Thanks a lot, help most appreciated.
